---

- name: Verify
  hosts: powershell_group
  vars:
    is_container: false
  pre_tasks:
    - name: Debug | var ansible_facts['virtualization_type']
      ansible.builtin.debug:
        var: ansible_facts['virtualization_type']
    - name: Set fact is_container
      ansible.builtin.set_fact:
        is_container: true
      when: >
        (ansible_facts['virtualization_type'] is defined and
          (ansible_facts['virtualization_type'] == "docker" or ansible_facts['virtualization_type'] == "containerd"
           or ansible_facts['virtualization_type'] == "container"
          )
        )
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Validate that needed packages are present
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['powershell'] is defined

    - name: Check powershell config
      ansible.builtin.stat:
        path: /opt/microsoft/powershell/7/powershell.config.json
      register: cfg
    - name: Validate powershell config is present
      ansible.builtin.assert:
        that: cfg.stat.exists and cfg.stat.size != 0 and cfg.stat.mode == '0644'

    - name: Run few powershell
      ansible.builtin.command: "{{ item }}"
      loop:
        - pwsh -Command Get-ExecutionPolicy
        - pwsh -Command Get-ExperimentalFeature
        - pwsh -File /opt/microsoft/powershell/7/Modules/PSReadLine/SamplePSReadLineProfile.ps1
        # RemoteSigned
        - pwsh -Command iex "((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      changed_when: false
      failed_when: false
    - name: List powershell logs files
      ansible.builtin.command: "find /var/log/powershell/ -ls"
      changed_when: false
      failed_when: false
    - name: Get transcription logs matches
      ansible.builtin.command: "grep {{ item }} /var/log/powershell/transcription/*/PowerShell_transcript.*.txt"
      loop:
        - Get-ExecutionPolicy
        - Get-ExperimentalFeature
        - /opt/microsoft/powershell/7/Modules/PSReadLine/SamplePSReadLineProfile.ps1
        - iex "((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      changed_when: false
      when:
        - not is_container|bool
